### ISSUE TITLE
Version 3.3.5 is missing system directory contents

### ISSUE THREAD

**Issue by bistory** [kohana/kohana#102]
Hello,

First thanks for continuing to update this framework.

The last version miss the system directory's content.
In this URL https://github.com/kohana/kohana/releases try to download an archive file and open the system directory... It is empty :-)

**Comment by gnovaro** [comment]
Thomas please download the zip version. I see the tar.gz have
empty system directiory.

On Sun, Mar 27, 2016 at 2:06 PM, Thomas Lété notifications@github.com
wrote:

> Hello,
> 
> First thanks for continuing to update this framework.
> 
> The last version miss the system directory's content.
> In this URL https://github.com/kohana/kohana/releases try to download an
> archive file and open the system directory... It is empty :-)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/kohana/kohana/issues/102

## 

_Gustavo A. Novaro_
Celular: +54 9 11 15-5757-7730
Seguime en Twitter: @gnovaro https://twitter.com/#%21/gnovaro

**Comment by bistory** [comment]
You are right, but the "Source code" zip has it empty too :)
Thanks anyway !

**Comment by acoulton** [comment]
@bistory that is expected. The "Source code" archives are simply archives of this repository, and you need to run `git submodule update --recursive` to pull in the other modules (which are all separate git repositories). The full version ZIP contains those modules as well, as a convenience.

FYI I'd actually recommend moving over to installing Kohana and just the modules you're actually using with composer instead of downloading a "complete" release.

**Comment by bistory** [comment]
Thanks, I didn't know Kohana was compatible with composer, I'll switch to use it :)
