### ISSUE TITLE
Have a `VENDOR` path predefined in `index.php`

### ISSUE THREAD

**Issue by enov** [kohana/kohana#26]
I think we need to have a `VENDOR` path predefined in `index.php` because some Kohana modules are registered with Composer/Packagist as a standard module.

For example:
https://github.com/Zeelot/kohana-media
(see the discussion here: https://github.com/Zeelot/kohana-media/pull/16)

**Comment by shadowhand** [comment]
+1 we do this in ushahidi/lamu too. (edit: oops, clicked the close button by accident)

**Comment by lenton** [comment]
Would be great if Kohana fully embraced composer where you install kohana/core and all the modules you need before using the framework.

**Comment by shadowhand** [comment]
+1 for installing everything with composer.

**Comment by pocesar** [comment]
+1

**Comment by mintbridge** [comment]
+1

**Comment by acoulton** [comment]
+1 - the only change required for installing with composer is to update the composer.json in kohana/kohana and any build/test scripts that currently pull or update submodules. The core and core modules already have full composer support.

However we presumably still want to keep the explicit Kohana::modules and using the Kohana autoloader (rather than falling back to Composer's) as that's the only way to support the cascading file system.

**Comment by enov** [comment]
@acoulton , exactly, similar to this one, courtesy of @happyDemon:

https://github.com/happyDemon/kohana-composer-bootstrap

And I suggest to always have a non-composer, full-stack Kohana build with all submodules, to be downloaded from Kohana website, for non-composer users.

**Comment by seyfer** [comment]
+1

https://github.com/kohana/kohana/issues/60

**Comment by localheinz** [comment]
:+1: for moving away from using Git submodules and using Composer.

**Comment by enov** [comment]
@lenton we should probably close this too?

**Comment by lenton** [comment]
@enov Yep, there's no real need for a `VENDOR` global variable now.
