### ISSUE TITLE
"git submodule status" trouble 

### ISSUE THREAD

**Issue by ghost** [kohana/kohana#68]
If i wrote this to console (ofc, modules and system folders from my profject are submodules, chained to your repository) and i saw that: 
![default](https://cloud.githubusercontent.com/assets/1884457/5958571/f65db0fa-a7d6-11e4-8355-5537d4f178bd.png)
Versions of modules and "system" folder are 3.2.*. But it is not true, because i use last (3.3.3.1 uluru version):
![default](https://cloud.githubusercontent.com/assets/1884457/5958574/04801a6a-a7d7-11e4-84cb-540642bbabb2.png)

**Comment by enov** [comment]
`git submodule status` calls `git describe` to show the tags in the parenthesis.

`git describe`, by default, only shows annotated tags. Unfortunately, some of the release tags, including the tags I created when releasing v3.3.3.1, are lightweight tags.

The problem is mostly solved in v.3.4, as we do not use submodules anymore.

**Comment by ghost** [comment]
Ok, thanks for answer. You mean, that you will not use git submodules in Kohana 3.4, or i understood that not correctly?

**Comment by enov** [comment]
Yeah, Kohana 3.4 [fully integrates with composer](https://github.com/kohana/kohana/pull/41).

**Comment by ghost** [comment]
Oh, okay, nice! That is another one feature, what we (community) should learn to use Kohana 3.4.

Issue closed.
