### ISSUE TITLE
[PHP7] Fatal Error in Kohana_Kohana_Exception

### ISSUE THREAD

**Issue by Invision70** [kohana/kohana#96]
Uncaught TypeError: Argument 1 passed to Kohana_Kohana_Exception::handler() must be an instance of Exception, instance of Error given ...

in
`public static function handler(Exception $e)`

Reason:
removed `mysql_*` functions
`Kohana_Database_MySQL->connect()`

**Comment by Invision70** [comment]
Hotfix `index.php`file

```
.... 
echo Request::factory(TRUE, array(), FALSE)
        ->execute()
        ->send_headers(TRUE)
        ->body();
```

Add wrapper

```
try
{
...
echo Request::factory(TRUE, array(), FALSE)
        ->execute()
        ->send_headers(TRUE)
        ->body();
}
catch (Error $e) //  php7 Throwable
{
    throw new ErrorException($e->getMessage(), $e->getCode(), 0, $e->getFile(), $e->getLine());
}
```

OR

If `Exception $e` replace to `Throwable $e` in `Kohana_Kohana_Exception` class its work! But... only for php 5.7.
There are other ideas? :)

**Comment by enov** [comment]
Hey @Invision70! This is related to https://github.com/kohana/core/issues/642. Unfortunately, there is no way to fix this in the core without breaking BC. We'll have support for PHP 7.0 in next hopeful Kohana release.

I am also not sure if your hack in the bootstrap is a good idea. What happens when an `Error` is raised before the code had reached your `try` block?

Thanks.
